### PR TITLE
Fix permission denied when writing configs

### PR DESCRIPTION
**Pull request by theJian**
## Description

Added `:z` to avoid permission denied error on Red Hat base distribution with an SELinux enforcing policy

## Motivation and Context

Fix: #1432 

## How Has This Been Tested?

Tested on Fedora 28 Silverblue.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dschaper** [comment]
It's already in the readme.

image

**Comment by theJian** [comment]
Yes, I realized that it has been mentioned in the following chapter. Initially, I was following the instructions and stuck for a few hours trying to figure out what was wrong before continuing to read the readme.

**Comment by dschaper** [comment]
Have you tested that your changes do not break non-SELinux installs? Those are by far the most common server configurations. 

I don't really see a need for this PR that changes everything for a small number of edge cases.

**Comment by theJian** [comment]
Actually, I'm thinking of just leaving comments for SELinux users without changing the default config file, so that most people can ignore it and people who were running SElinux distro can be informed before running into this error.

Let me know what you think.

**Pull request closed without merging**
