### PR TITLE
Update docker-compose version

### PR DESCRIPTION
**Pull request by jauderho**
## Description
Update docker-compose version

## Motivation and Context
There has been quite a few changes, see changelog https://docs.docker.com/compose/release-notes/

1.29.2🔗

(2021-05-10)
Miscellaneous

    Removed the prompt to use docker compose in the up command.

    Bumped py to 1.10.0 in requirements-indirect.txt.

1.29.1

(2021-04-13)
Bugs

    Fixed invalid handler warning on Windows builds.

    Fixed config hash to trigger container re-creation on IPC mode updates.

    Fixed conversion map for placement.max_replicas_per_node.

    Removed extra scan suggestion on build.

1.29.0

(2021-04-06)
Features

    Added profile filter to docker-compose config.

    Added a depends_on condition to wait for successful service completion.

Miscellaneous

    Added an image scan message on build.

    Updated warning message for --no-ansi to mention --ansi never as alternative.

    Bumped docker-py to 5.0.0.

    Bumped PyYAML to 5.4.1.

    Bumped python-dotenv to 0.17.0.

1.28.6

(2021-03-23)
Bug fixes

    Made --env-file relative to the current working directory. Environment file paths set with --env-file are now relative to the current working directory and override the default .env file located in the project directory.

    Fixed missing service property storage_opt by updating the Compose schema.

    Fixed build extra_hosts list format.

    Removed additional error message on exec.

Miscellaneous

    Added compose.yml and compose.yaml to the default filename list.

1.28.5

(2021-02-26)
Bugs

    Fixed the OpenSSL version mismatch error when shelling out to the SSH client (via bump to docker-py 4.4.4 which contains the fix).

    Added missing build flags to the native builder: platform, isolation and extra_hosts.

    Removed info message on native build.

    Fixed the log fetching bug when service logging driver is set to ‘none’.

1.28.4

(2021-02-18)
Bug fixes

    Fixed SSH port parsing by bumping docker-py to 4.4.3.

Miscellaneous

    Bumped Python to 3.7.10.

1.28.3

(2021-02-17)
Bug fixes

    Fixed SSH hostname parsing when it contains a leading ‘s’/’h’, and removed the quiet option that was hiding the error (via docker-py bump to 4.4.2).

    Fixed key error for --no-log-prefix option.

    Fixed incorrect CLI environment variable name for service profiles: COMPOSE_PROFILES instead of COMPOSE_PROFILE.

    Fixed the fish completion.

Miscellaneous

    Bumped cryptography to 3.3.2.

    Removed the log driver filter.

For a list of PRs and issues fixed in this release, see Compose 1.28.3.
1.28.2

(2021-01-26)
Bug fixes

    Revert to Python 3.7 bump for Linux static builds

    Add bash completion for docker-compose logs|up --no-log-prefix

Miscellaneous

    CI setup update

1.28.0

(2021-01-20)
Features

    Added support for NVIDIA GPUs through device requests.

    Added support for service profiles.

    Changed the SSH connection approach to the Docker CLI by shelling out to the local SSH client. Set the COMPOSE_PARAMIKO_SSH=1 environment variable to enable the old behavior.

    Added a flag to disable log prefix.

    Added a flag for ANSI output control.

    Docker Compose now uses the native Docker CLI’s build command when building images. Set the COMPOSE_DOCKER_CLI_BUILD=0 environment variable to disable this feature.

Bug fixes

    Made parallel_pull=True by default.

    Restored the warning for configs in non-swarm mode.

    Took --file into account when defining project_dir.

    Fixed a service attach bug on compose up.

Miscellaneous

    Added usage metrics.

    Synced schema with COMPOSE specification.

    Improved failure report for missing mandatory environment variables.

    Bumped attrs to 20.3.0.

    Bumped more_itertools to 8.6.0.

    Bumped cryptograhy to 3.2.1.

    Bumped cffi to 1.14.4.

    Bumped virtualenv to 20.2.2.

    Bumped bcrypt to 3.2.0.

    Bumped GitPython to 3.1.11.

    Bumped docker-py to 4.4.1.

    Bumped Python to 3.9.

    Linux: bumped Debian base image from stretch to buster (required for Python 3.9).

    macOS: Bumped OpenSSL 1.1.1g to 1.1.1h, and Python 3.7.7 to 3.9.0.

    Bumped PyInstaller to 4.1.

    Relaxed the restriction on base images to latest minor.

    Updated READMEs.

1.27.4

(2020-09-24)
Bug fixes

    Removed path checks for bind mounts.

    Fixed port rendering to output long form syntax for non-v1.

    Added protocol to the Docker socket address.

1.27.3

(2020-09-16)
Bug fixes

    Merged max_replicas_per_node on docker-compose config.

    Fixed depends_on serialization on docker-compose config.

    Fixed scaling when some containers are not running on docker-compose up.

    Enabled relative paths for driver_opts.device for local driver.

    Allowed strings for cpus fields.

1.27.2

(2020-09-10)
Bug fixes

    Fixed bug on docker-compose run container attach.

1.27.1

(2020-09-10)
Bug fixes

    Fixed docker-compose run when service.scale is specified.

    Allowed the driver property for external networks as a temporary workaround for the Swarm network propagation issue.

    Pinned the new internal schema version to 3.9 as the default.

    Preserved the version number configured in the Compose file.

1.27.0

(2020-09-07)
Features

    Merged 2.x and 3.x Compose formats and aligned with COMPOSE_SPEC schema.

    Implemented service mode for ipc.

    Passed COMPOSE_PROJECT_NAME environment variable in container mode.

    Made run behave in the same way as up.

    Used docker build on docker-compose run when COMPOSE_DOCKER_CLI_BUILD environment variable is set.

    Used the docker-py default API version for engine queries (auto).

    Parsed network_mode on build.

Bug fixes

    Ignored build context path validation when building is not required.

    Fixed float to bytes conversion via docker-py bump to 4.3.1.

    Fixed the scale bug when the deploy section is set.

    Fixed docker-py bump in setup.py.

    Fixed experimental build failure detection.

    Fixed context propagation to the Docker CLI.

Miscellaneous

    Bumped docker-py to 4.3.1.

    Bumped tox to 3.19.0.

    Bumped virtualenv to 20.0.30.

    Added script for Docs synchronization.

1.26.2

(2020-07-02)
Bug fixes

    Enforced docker-py 4.2.2 as minimum version when installing with pip.

1.26.1

(2020-06-30)
Features

    Bumped docker-py from 4.2.1 to 4.2.2.

Bug fixes

    Enforced docker-py 4.2.1 as minimum version when installing with pip.

    Fixed context load for non-docker endpoints.

1.26.0

(2020-06-03)
Features

    Added docker context support.

    Added missing test dependency ddt to setup.py.

    Added --attach-dependencies to command up for attaching to dependencies.

    Allowed compatibility option with COMPOSE_COMPATIBILITY environment variable.

    Bumped Pytest to 5.3.4 and add refactor compatibility with the new version.

    Bumped OpenSSL from 1.1.1f to 1.1.1g.

    Bumped certifi from 2019.11.28 to 2020.4.5.1.

    Bumped docker-py from 4.2.0 to 4.2.1.

Bug fixes

    Properly escaped values coming from env_files.

    Synchronized compose-schemas with upstream (docker/cli).

    Removed None entries on exec command.

    Added distro package to get distro information.

    Added python-dotenv to delegate .env file processing.

    Stopped adjusting output on terminal width when piped into another command.

    Showed an error message when version attribute is malformed.

    Fixed HTTPS connection when DOCKER_HOST is remote.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dschaper** [comment]
What does this change gain us in the building of the images? I don't see anything that would require the update but I may be missing something.

**Comment by jauderho** [comment]
Other than the usual fixes, it moves the bar forward regarding Docker's cleanup of docker-compose.

- Docker Compose version parameter will be ignored going forward
- compose.yml and compose.yaml

 
See reference links for the Compose spec

- https://docs.docker.com/compose/compose-file/
- https://github.com/compose-spec/compose-spec/blob/master/spec.md

**Comment by dschaper** [comment]
Thanks, I'm hesitant to make changes for the sake of making changes when things work as they are currently. 

I'll leave this for the other developers but I'd vote no on this one.

**Comment by jauderho** [comment]
That's fine but I would think that at some point, the code base would have updated dependencies. 

I can close this request out if there is no interest.

**Pull request closed without merging**
