### PR TITLE
Dev to Master to release 4.4

### PR DESCRIPTION
**Pull request by diginc**
After this, we'll tag v4.3.5 against the master branch which should trigger the new circle-ci automated deploy for that docker hub tag.

the 'latest' tag will have to be pushed manually still I believe, I never wrote automation for that.

### CODE REVIEW

**Comment by diginc** [comment]
One small addition with #579 is getting re-built and will be out on docker hub in the next 10-15m.  Please report any feedback on `pihole/pihole:dev` here before we merge and tag `:latest`

**Comment by dschaper** [comment]
:shipit:

**Comment by dschaper** [comment]
Do we need to adjust the required checks?
```
-travis
+circlice
```

**Comment by PromoFaux** [comment]
Yeah, travis no longer required AFAIK

**Pull request merged**
