### PR TITLE
Bump alpine to 3.20

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

Update Alpine base from 3.19 to 3.20

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by yubiuser** [comment]
Do you want also upgrade here?
https://github.com/pi-hole/docker-pi-hole/blob/development-v6/test/Dockerfile

**Comment by PromoFaux** [comment]
FP'd

**Comment by PromoFaux** [comment]
Perhaps not as simple as that... one to investigate

**Comment by rdwebdesign** [comment]
I think there is an issue with `python3-dev`.

**Comment by yubiuser** [comment]
Another approach would be to remove the `sed` and the same monkeypatch as used in `core`

https://github.com/pi-hole/pi-hole/blob/be5a8dc51a7b3e7ec3b40a9c815dee1c866ea2d4/test/conftest.py#L21-L35

**Comment by yubiuser** [comment]
@PromoFaux

See my commit and last comment. Which way do you prefer?

**Comment by PromoFaux** [comment]
Ah, Sorry - didn't see that you'd pushed a commit before your comment.

If I've understood it correctly, I think the monkeypatch is probably more resiliant as it is one less thing to have to update every time the python version updates?

**Comment by yubiuser** [comment]
I think I found a nice solution. My concern with the monkeypatch is that it is way harder to understand than a small sed command

**Review by yubiuser — APPROVED** [review]

**Comment by PromoFaux** [comment]
Ah yeah, that's good!

**Pull request merged**
