### PR TITLE
Remove some unnessacery dependencies

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

Partly addresses https://github.com/pi-hole/docker-pi-hole/issues/1359

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by PromoFaux** [comment]
Needs: https://github.com/pi-hole/docker-pi-hole/issues/1358

**Comment by PromoFaux** [comment]
Comment to trigger stale

**Comment by PromoFaux** [comment]
Just spotted that @DL6ER edited his comment here: https://github.com/pi-hole/docker-base-images/pull/69#issuecomment-1627782740

I think this means that we probably _cannot_ drop ` libidn` & `nettle`. Clarification needed

**Review by DL6ER — APPROVED** [review]
They can be removed here (Alpine only), they just can't be removed in the installer script as this may be used on Debian-based systems

**Comment by PromoFaux** [comment]
OK, thanks that's good to know

**Pull request merged**
