### PR TITLE
remove resolv.conf code

### PR DESCRIPTION
**Pull request by diginc**
v5.0 removed the need for localhost system/container Resolv.conf DNS AFAIK.

## Description
Deleted code that shouldn't be needed.

## Motivation and Context
Cleaning cruft

## How Has This Been Tested?
Locally for a day or so.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DaveSpe** [comment]
Please merge this. My pi-hole died today. 
I like pi, and I like hole.

**Comment by dschaper** [comment]
It doesn't look like there is any difference between this branch and what is on master.

**Comment by diginc** [comment]
Helps if I commit.

**Comment by dschaper** [comment]
Is the deploy step failure known or still an issue to fix?

**Comment by diginc** [comment]
I might need to pull in the changes to `dev` branch Dockerfile_build into master to get this deploying again.  Docker version / circleci host issue incompatibility that it happens my new debian build image fixed.

Also forgot to mention to @DaveSpe , this is a superficial change and shouldn't be breaking anyone's pi-hole since the resolv.conf messages are soft warnings, not hard errors.  You might have another issue so please file a new issue if that is the case (don't respond with it here).

**Pull request merged**
