### PR TITLE
Reduce git clone depth

### PR DESCRIPTION
**Pull request by jauderho**
## Description
Reduce git clone depth

## Motivation and Context
This will reduce the size of the docker image

## How Has This Been Tested?
git clone vs. git clone --depth 10

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by DL6ER** [comment]
Why not reduce it to one?

**Comment by PromoFaux** [comment]
May cause issues with the version checker (though less of an issue in docker)

**Comment by PromoFaux** [comment]
Something worth noting, this actually increases the size of the image by 2MB when I build it locally...

```
REPOSITORY                   TAG                           IMAGE ID       CREATED          SIZE
pihole                       v5.8.1-amd64-buster           30544ee9dd9e   2 minutes ago    340MB
pihole/pihole                test-git-depth-amd64-buster   30544ee9dd9e   2 minutes ago    340MB
pihole/pihole                dev-amd64-buster              63763e46d4d2   5 minutes ago    338MB
```

**Comment by jauderho** [comment]
@dschaper GitHub was acting oddly last night so I was having trouble having this branch show up reliably. If I can't get it to work, I'll create a new pull request.

> Why not reduce it to one?

This is possible but only saves about 1.3MB so not a big gain there.

**Pull request closed without merging**
