### PR TITLE
Adding CORS_HOSTS to PHP environment

### PR DESCRIPTION
**Pull request by adyanth**
This makes it possible to enables CORS per domain. 

## Description

Adds a new environment variable CORS_HOSTS which is a list of comma separated domains to PHP.

## Motivation and Context

Fixes https://github.com/pi-hole/docker-pi-hole/issues/864
Refer https://github.com/bastienwirtz/homer/issues/194
Works along with https://github.com/pi-hole/AdminLTE/issues/1820

## How Has This Been Tested?

Tested by bind mounting my docker container. Using it with those changes in place for the past week.
Just adds another environment variable, that is used by auth.php in AdminLTE (changes will be submitted as a PR)

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Documentation change would be to showcase the new env var and its usage. I am not sure where all the changes need to be made.

Usage is adding the below to docker-compose environment or docker run -e

`CORS_HOSTS=test.domain.com,example.com`

### CODE REVIEW

**Comment by adyanth** [comment]
Bump, Can someone review this?

**Comment by adyanth** [comment]
@PromoFaux This is the corresponding PR for https://github.com/pi-hole/AdminLTE/pull/1822
I'll change the same tab to space here too.

**Comment by PromoFaux** [comment]
Merging into `dev`, but this wont be fully provable until the next nightly is built as the changes required in the web interface are in the `devel` branch

**Comment by PromoFaux** [comment]
@adyanth - I've kicked off a build of the `nightly` tag (https://github.com/pi-hole/docker-pi-hole/actions/runs/997487707)

Would you be able to give it a try once it has built and confirm it works as expected? The CORS_HOSTS variable should be working in that one. Oh, And I meant to add, can you please PR a note about `CORS_HOSTS` variable to the readme on this repository? Thanks

**Comment by adyanth** [comment]
Hey @PromoFaux This build includes this PR (https://github.com/pi-hole/AdminLTE/pull/1822), right? I will test it out by swapping the container I use daily for pihole/pihole:nightly, would be able to test if that breaks something else as well.

Sure, will submit that PR soon.

**Comment by PromoFaux** [comment]
> I will test it out by swapping the container I use daily

Just make sure you've got a backup! - the `nightly` container pulls from the various `development` branches (and is allowed to break at any time). You should be fine, but there may be breaking changes that cause issues should you roll back to the main container.

**Comment by adyanth** [comment]
100%, that's why I have two of them serving all devices, one breaks, I'm still up!

**Comment by adyanth** [comment]
Initial checks, works as expected, tried with the homer thing this aimed to solve, and the CLI to be sure. Will run this for a day and confirm back if something else did break, Otherwise, looks good!

Here is the `curl` outputs with the env set to `CORS_HOSTS: home.adyanth.lan,home.adyanth.site,test.domain.com`

```
C:\Users\adyan>curl -v https://pihole-nuc.adyanth.site/admin/api.php -H "Origin: https://test.domain.com"
*   Trying 10.10.10.3...
* TCP_NODELAY set
* Connected to pihole-nuc.adyanth.site (10.10.10.3) port 443 (#0)
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 194 bytes...
* schannel: sent initial handshake data: sent 194 bytes
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 4032
* schannel: encrypted data buffer: offset 4032 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: encrypted data got 830
* schannel: encrypted data buffer: offset 4862 length 5056
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: encrypted data got 195
* schannel: encrypted data buffer: offset 195 length 5056
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /admin/api.php HTTP/1.1
> Host: pihole-nuc.adyanth.site
> User-Agent: curl/7.55.1
> Accept: */*
> Origin: https://test.domain.com
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 924
* schannel: encrypted data buffer: offset 924 length 103424
* schannel: decrypted data length: 895
* schannel: decrypted data added: 895
* schannel: decrypted data cached: offset 895 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 895 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 895
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: https://test.domain.com
< Cache-Control: no-store, no-cache, must-revalidate
< Content-Length: 456
< Content-Type: application/json
< Date: Sun, 04 Jul 2021 12:32:30 GMT
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Server: lighttpd/1.4.53
< Set-Cookie: PHPSESSID=9dkei0cca5t8dd20gve038ooqk; path=/; HttpOnly
< X-Frame-Options: DENY
< X-Pi-Hole: The Pi-hole Web interface is working!
<
{"domains_being_blocked":81793,"dns_queries_today":189,"ads_blocked_today":23,"ads_percentage_today":12.169312,"unique_domains":83,"queries_forwarded":132,"queries_cached":26,"clients_ever_seen":9,"unique_clients":9,"dns_queries_all_types":180,"reply_NODATA":0,"reply_NXDOMAIN":7,"reply_CNAME":5,"reply_IP":3,"privacy_level":0,"status":"enabled","gravity_last_updated":{"file_exists":true,"absolute":1625401918,"relative":{"days":0,"hours":0,"minutes":0}}}* Connection #0 to host pihole-nuc.adyanth.site left intact

C:\Users\adyan>curl -v https://pihole-nuc.adyanth.site/admin/api.php -H "Origin: https://failtest.domain.com"
*   Trying 10.10.10.3...
* TCP_NODELAY set
* Connected to pihole-nuc.adyanth.site (10.10.10.3) port 443 (#0)
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 194 bytes...
* schannel: sent initial handshake data: sent 194 bytes
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 4032
* schannel: encrypted data buffer: offset 4032 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: encrypted data got 830
* schannel: encrypted data buffer: offset 4862 length 5056
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 2/3)
* schannel: encrypted data got 195
* schannel: encrypted data buffer: offset 195 length 5056
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with pihole-nuc.adyanth.site port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /admin/api.php HTTP/1.1
> Host: pihole-nuc.adyanth.site
> User-Agent: curl/7.55.1
> Accept: */*
> Origin: https://failtest.domain.com
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 605
* schannel: encrypted data buffer: offset 605 length 103424
* schannel: decrypted data length: 576
* schannel: decrypted data added: 576
* schannel: decrypted data cached: offset 576 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 576 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 576
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< Cache-Control: no-store, no-cache, must-revalidate
< Content-Length: 183
< Content-Type: text/html; charset=UTF-8
< Date: Sun, 04 Jul 2021 12:32:40 GMT
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Pragma: no-cache
< Server: lighttpd/1.4.53
< Set-Cookie: PHPSESSID=et4oeht97moktvi1icg7uoc7r0; path=/; HttpOnly
< X-Frame-Options: DENY
< X-Pi-Hole: The Pi-hole Web interface is working!
<
Failed CORS: failtest.domain.com vs 0.0.0.0, 192.168.144.20, pihole-nuc.adyanth.site, pi.hole, localhost, pihole-nuc.adyanth.site, home.adyanth.lan, home.adyanth.site, test.domain.com* Connection #0 to host pihole-nuc.adyanth.site left intact
```

Here is Homer :)
image

**Comment by adyanth** [comment]
No issues seen till now, looks good!

**Comment by PromoFaux** [comment]
👍 If you want to run something that includes it (and is a bit more stable than `nightly`) we pushed a `:beta-v5.9` tag last night:

https://discourse.pi-hole.net/t/join-us-beta-testing-pi-hole-ftl-v5-9-web-v5-6-and-core-v5-4/48021/6

**Comment by adyanth** [comment]
Awesome, will switch to it!

**Pull request merged**
