### PR TITLE
drop the `/v8` from `linux/arm64/v8`

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

CI is using `linux/arm64/v8` in the `platform` matrix, we should be using `linux/arm64`. I think. Lets see what the tests say...

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by PromoFaux** [comment]
Looks good so far: 

image

**Comment by PromoFaux** [comment]
Actually might have one more commit for this.. hold reviews please

**Comment by PromoFaux** [comment]
Ready for review

**Comment by yubiuser** [comment]
I wonder if we now still need both `TARGETPLATFORM` set from https://github.com/pi-hole/docker-pi-hole/commit/5c7ff5c539c75c1aab7fcd3d392f78d26e246d75

(I get always confused by the nested docker build on top of docker builds)

**Comment by PromoFaux** [comment]
That was what my deleted comment was about.. I tried to build locally with that removed (run as `PLATFORM=linux/arm64/v8 ./build-and-test.sh` and the result was the following:

image

So that part is still needed I believe.

**Review by yubiuser — APPROVED** [review]

**Comment by PromoFaux** [comment]
Both `--platform=linux/arm64` and `--platform=linux/arm64/v8` are valid and will produce a `linux/arm64` image (per [the link you shared earlier](https://github.com/BretFisher/multi-platform-docker-build#recommended-approach-for-curl-and-wget-commands-in-multi-platform-dockerfiles)

The docker-in-docker stuff probably adds some complexity, and something we should look at finding another way around one day. But not this day. For now we can just use the simple form of the `platform` argument

**Comment by PromoFaux** [comment]
Watching the next publish like a hawk...

**Pull request merged**
