### PR TITLE
Simplify Dockerfile configuration.

### PR DESCRIPTION
**Pull request by lightswitch05**
Simplify Dockerfile configuration by dropping the various Dockerfile flavors.

## Description

* Simplify docker builds by consolidating all arch's into a single Dockerfile and using ARGS for the various differences
* Introduce docker-compose based builds (build.yml) for simple management of the various args differences

## Motivation and Context
My original goal tonight was to introduce GitHub actions, but I quickly realized there is a lot of moving parts with this build. After some investigation, it seemed some complexities could be simplified - particularly with the various Dockerfile flavors.

## How Has This Been Tested?
Just running local builds. While I did switch the build tool from plain Docker to docker-compose - I tried to keep the `Dockerfile.py` interface untouched to reduce further complications.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking changes which cleans up the code)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

☝️ I've changed the build logic, but I think that falls outside of the 'documentation' category.

### CODE REVIEW

**Comment by diginc** [comment]
Sorry about the conflicts, could you merge dev in?

**Comment by lightswitch05** [comment]
Sorry, I just saw this @diginc - no problem!

**Comment by lightswitch05** [comment]
Conflicts fixed. I know there has been some discussions about building multi-arch images and issues with manifests. This change **does** introduce `docker-compose` as the build tool (`build.yml`), but it wouldn't be a major change to switch back to a pure `docker` build. Compose is just nice for managing the different build args and not a requirement.

**Comment by lightswitch05** [comment]
I might do some more work in this project in the coming days. I’d like to base that work on these changes. Anything particular holding this back? Or just things moving slowly?

**Pull request merged**
