### PR TITLE
Update README.md to include detailed Ubuntu install tips

### PR DESCRIPTION
**Pull request by kaysond**
## Description
Include information about properly configuring name resolution on Ubuntu

## Motivation and Context
Addresses #503 

## How Has This Been Tested?
No testing required

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by kaysond** [comment]
Pinging @diginc do you have a moment to review?

**Comment by diginc** [comment]
systemd-resolver & netplan instructions look good.  What is the WEBPASSWORD_FILE addition / benefit?

**Comment by kaysond** [comment]
@diginc whoops i forgot about this and pushed something else. i've split that off to a separate branch and i'll submit another PR when I test it.

Also rebased this PR

**Comment by dschaper** [comment]
Does this need porting over to https://docs.pi-hole.net?

**Comment by kaysond** [comment]
@dschaper Do you mean to Docker section? I don't think its applicable to the automated install script since the script already disables the stub resolver and sets up /etc/resolvconf via some other tool I can't remember. Let me know and I can submit a PR

**Comment by dschaper** [comment]
The whole docker section on docs.pi-hole.net needs some attention. I'll look things over but it would be nice to have most of the README on docs.

**Pull request merged**
