### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by canepan**
Mention the required update to docker.io in additon to libseccomp2 on ARM

`{Please select 'base: dev' as target branch above! (you can delete this line)}`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by rdwebdesign** [comment]
Please, you need to sign off your commit adding:

```
Signed-off-by: your name <youremail@example.com>
```

---  

Also, your PR is pointing to the wrong branch:
dev_branch

You need to change the base branch, clicking on the "Edit" button (near the PR title, top right).
Please, point this PR to `dev` branch.

**Comment by dschaper** [comment]
Does it really need the docker.io change? So far just the libsec update has worked for most.

**Comment by canepan** [comment]
Most of the reports which are resolved by just the libseccomp2 update are already running Docker 20.x, where mentioned, and there is some report of the update not fixing the issue (which wasn't fixed for me until I also updated Docker).
Buster images for ARM can still be found, if this needs to be further tested.
Let me know if I should just drop the pull request: I am working to update it as requested

**Comment by canepan** [comment]
Sorry: I wasn't able to update this PR, and I created #1082 instead.

**Pull request closed without merging**
