### PR TITLE
Add QUERY_LOGGING missing export

### PR DESCRIPTION
**Pull request by damajor**
## Description

This change adds a missing export (QUERY_LOGGING) in order to set this value from docker environment variables.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lightswitch05** [comment]
Looks like these tests also failed due to the Python version change fixed in #704

**Comment by damajor** [comment]
Is there a way to run the checks again ?

**Comment by lightswitch05** [comment]
@damajor you'll need to rebase these changes off the latest `dev` branch before the tests can be successful.

**Comment by damajor** [comment]
Help for #720

**Review by PromoFaux — APPROVED** [review]
I was just about to say you'll need to add the relevant `change-setting` line, however I see that it is already there :)

**Pull request merged**
