### PR TITLE
Add idn2-utils to image as it is needed for pihole -q

### PR DESCRIPTION
**Pull request by yubiuser**
As the title says. Fixes a bug reported here: 
https://github.com/pi-hole/pi-hole/issues/5458#issuecomment-1783729929

### CODE REVIEW

**Comment by DL6ER** [comment]
Is `idn2` still used by `pihole -q` even when it queries FTL's API? We could easily expose FTL's own `idn` capabilities over the API if needed.

**Comment by yubiuser** [comment]
It was there when I wrote the v5 -> v6 update and I kept it. 

https://github.com/pi-hole/pi-hole/blob/0a193f98a43c1c914b836b0a1c2b02cf60b58ac8/advanced/Scripts/query.sh#L112-L113

**Comment by yubiuser** [comment]
Last commit should fix changes required after https://github.com/pi-hole/FTL/pull/1707

**Comment by PromoFaux** [comment]
@yubiuser rebase on `development-v6`, I've admin-crimed your latest commit there.

**Comment by PromoFaux** [comment]
Could (thinking out loud here) FTL handle the part of converting the `${domain}` value it is passed to punycode and lowercase itself?

**Comment by PromoFaux** [comment]
No scratch that, Not had my coffee - I misread your typings

**Comment by yubiuser** [comment]
Closing as https://github.com/pi-hole/FTL/pull/1715 works as expected.

`idn2` is not required anymore: https://github.com/pi-hole/pi-hole/pull/5468

**Pull request closed without merging**
