### PR TITLE
Dev to Master [5.2.1]

### PR DESCRIPTION
**Pull request by PromoFaux**

### CODE REVIEW

**Review by diginc — APPROVED** [review]
I'll update the docker hub readme to match this one manually too (they don't sync since we switched off docker hub building our image)

**Comment by PromoFaux** [comment]
@diginc where does the `build` job come into it?

**Comment by diginc** [comment]
IDK I saw that hanging on my other PR too.

**Comment by PromoFaux** [comment]
Odd. I just found the repo was still enabled in travis-ci.org, so I've turned that off. May have been that /shrug.

I've drafted the tag, is there anything that needs to be done before tagging?

**Comment by diginc** [comment]
I checked the `:dev` and `:master` tag and I don't think it actually  updated

```
pihole       |   Pi-hole version is v5.2 (Latest: v5.2.1)
pihole       |   AdminLTE version is v5.2 (Latest: v5.2.1)
pihole       |   FTL version is v5.3.1 (Latest: v5.3.2)
```

**Comment by diginc** [comment]
Nevermind, master wasn't quite done baking yet and it looks good now that its done.  Tagging should be good to go

dev being old might have been on my end - even though it said it pulled a new one...might have to look into that more.

**Comment by PromoFaux** [comment]
Hold on, just pulling dev now

**Comment by PromoFaux** [comment]
I think it might be from where I accidentally botched the CI

dev:
```
bash-4.3# docker exec -it pihole pihole -v
  Pi-hole version is v5.2 (Latest: v5.2)
  AdminLTE version is v5.2 (Latest: v5.2)
  FTL version is v5.3.2 (Latest: v5.3.1)
```
Master:
```
bash-4.3# docker exec -it pihole pihole -v
  Pi-hole version is v5.2.1 (Latest: v5.2.1)
  AdminLTE version is v5.2.1 (Latest: v5.2.1)
  FTL version is v5.3.2 (Latest: v5.3.2)
```

**Comment by PromoFaux** [comment]
I guess a push of something innocuous into dev should fix it

**Comment by PromoFaux** [comment]
> I think it might be from where I accidentally botched the CI

OH. Yes. I pushed the stuff into dev before the core repos were tagged. Which is probably what went wrong?

**Pull request merged**
