### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MeiRos**
Transitioning away from jwilder/nginx-proxy
Please see #1304 for more details

## Description

The link wasn't working so it's fixed now. Also changed jwilder/proxy to nginxproxy in the text.

## How Has This Been Tested?

Tested by clicking it. No more 404.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by gardn701** [comment]
I think this fixes the issue I have.  I just found pihole and was reading the setup instructions.  I have a reverse proxy using port 80 and I wanted to see the example about reverse proxy but the link is broken.  Can that get fixed?

**Comment by PromoFaux** [comment]
Seems this got updated in another PR - but thanks anyway!

**Comment by MeiRos** [comment]
Hi @PromoFaux !
Because I want to learn, can you tell me what is wrong with this pr? It was made August 17th but didn't get accept or any comments.

**Comment by PromoFaux** [comment]
Sure, if you look at the readme on the master branch, these changes have already been made - so this PR must have slipped us by - very sorry about that, you haven't done anything wrong :)

**Pull request closed without merging**
