### PR TITLE
Update dependancies

### PR DESCRIPTION
**Pull request by lightswitch05**
## Description
Bump some package versions

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dschaper** [comment]
Is this a duplicate of #850 (and the other Dependabot PRs?)

**Comment by lightswitch05** [comment]
@dschaper yes, I squashed them into into a single commit and rebuilt the `Pipfile.lock`

**Comment by dschaper** [comment]
Okay, you can tell Dependabot to merge the other PRs, I just did that with #850.

**Comment by lightswitch05** [comment]
Bummer :( each of them will produce conflicts and still need a new lock file afterwards

**Comment by dschaper** [comment]
Dependabot should take care of all of that.

**Comment by lightswitch05** [comment]
Oh neat, I didn't realize that

**Comment by dschaper** [comment]
In the other repos it is set to automatically merge when it's given an approval from someone with write access but it looks like it may still be set to requiring an `@dependabot merge` comment to merge it. It then will rebase any outstanding PRs that are affected by the merge changes.

In hindsight your PR would have done all the updates at once and probably would have been a better idea instead of waiting for each PR to rebase.

**Pull request closed without merging**
