### PR TITLE
Add support for choosing PADD branch in build script

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

TItle. Also fixes casing of `as` -> `AS` in the Dockerfile which was prompted by:

```
 4 warnings found (use --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 4)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 72)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 88)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 93)
```

Edit: Also fixes the currently failing builds on `development-v6` by removing a trailing `.` from the pytest version in requirements.txt. Not sure how it was working before, but the fix is simple

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by PromoFaux** [comment]
Hmmm, what's going on here then?

**Comment by PromoFaux** [comment]
There are also 2 warnings on the build of the test image, not really sure how to fix them, even after [reading the docs](https://docs.docker.com/reference/build-checks/json-args-recommended/). But they are only warnings I guess - not overly important!

```
 2 warnings found (use --debug to expand):
 - JSONArgsRecommended: JSON arguments recommended for ENTRYPOINT to prevent unintended behavior related to OS signals (line 21)
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 22)
```

**Comment by yubiuser** [comment]
Why did you decide not to use the `SHELL` instruction?

**Comment by PromoFaux** [comment]
It didn't work when I tried it initially. But this also works

**Comment by yubiuser** [comment]
I had a look at the code again - do we really need entrypoint.sh? All it does is to set
`set -ex` and invoke `cmd.sh`. But the former is done in `cmd.sh` as well and the latter is the `CMD` itself....

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
