### PR TITLE
Synology sudo audit error fix, disable audit in pam modules

### PR DESCRIPTION
**Pull request by diginc**
## Description
Older kernels get some fatal sudo audit errors in docker images that utilize su/sudo, which is sprinkled throughout pi-hole.

## Motivation and Context
Fix it

## How Has This Been Tested?
Automated tests, lots of people testing in issue https://github.com/pi-hole/docker-pi-hole/issues/243

## Types of changes
Moved non pi-hole stuff to a new setup.sh script, split it into it's on RUN step because it is a REALLY long manual build of PAM modules and docker caching is going to be required to maintain sanity.

Increased the docker image size, but haven't had time to hunt down where that size is.  Still running the clean up of /var/lib/apt and also added a deletion of the manually re-built debs for pam.

## Checklist:
- [x] My code follows the code style of this project.
- [?] My change requires a change to the documentation.
- [?] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dschaper** [comment]
Would removing `sudo` from the calls if the running user was root help?

**Comment by diginc** [comment]
As I typed that description the same idea occurred to me, I think it's `su` as much as `sudo` after reviewing some of the original links about the issue:

- https://github.com/moby/moby/issues/5899 - noted this comment about it being [more than just su](https://github.com/moby/moby/issues/5899#issuecomment-54107108)
- https://github.com/sequenceiq/docker-pam/
- https://github.com/sequenceiq/docker-pam/blob/master/ubuntu-14.04/Dockerfile

It maybe a lot of work to remove the pi-hole references, if we can get the size down then this PR isn't as contentious for me.

**Comment by dschaper** [comment]
Okay, my plan is to borrow some of the priv functions from `get.docker.com` and try to remove the `sudo` calls with `sh -c` if the user is UID/GID 0.

**Comment by diginc** [comment]
Since this proved it worked, I think I should do this the right way and split out the synology pam debian modification into it's own image which this image uses as it's basis.  This makes the build faster & allows anyone else who may need a pam w/disable audit as a debian image to re-use it.

For now I think I'll just do amd64 since I don't think synology provides docker for anything but their intel models.

**Comment by Azzhoe** [comment]
@diginc so currently I am using the official pihole/pihole:synology. Do I need to redownload it again using pihole/pihole:development instead in order to stay up to date with the latest working version for my Synology NAS?

**Pull request merged**
