### PR TITLE
Publish images to GHCR alongside DockerHub

### PR DESCRIPTION
**Pull request by ferferga**
## Description
Publishes the same image to GHCR alongside DockerHub.

**Before merging, you must ensure that GITHUB_TOKEN have permissive permissions (the defaults). See [this article](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token= for more information**.

## Motivation and Context
DockerHub is having tighter limits for pulling and GHCR is, honestly, a great alternative where a lot of containers are being published as well. It's also faster to pull from GHCR in my area than DockerHub.

## How Has This Been Tested?
There's no proper way for me to test this as it's only a simple CI change and I don't have token permissions. However, I based my changes in my previous work for GHCR publishing in [Jellyfin Vue](https://github.com/jellyfin/jellyfin-vue/blame/master/.github/workflows/docker.yml) and [Jellyfin's packaging pipelines](https://github.com/jellyfin/jellyfin-metapackages/pull/11)

## Additional Info
I have a script meant to be run as a cron to sync tags that are present in DockerHub but not in GHCR [here](https://gist.github.com/ferferga/7dc7bef353c2f41520a1a42d12f5e41c) (which is really useful when DockerHub limits are reached while pulling the images for syncing). Could be used by some of the maintainers of this project to make GHCR a 1:1 mirror with DockerHub, including older images.

Also, you might want to consider [implementing this another script](https://gist.github.com/ferferga/93ca1ab3056257d05f6e33af0d6ead49) in a cron GitHub Action that prunes images not associated with any tag (something that DockerHub does automatically, but GHCR keeps all the dangling images by default) to keep the package clean. **I can make a PR after this one is merged if this behaviour is desired for you**.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by PromoFaux** [comment]
You've read my mind... I started looking at doing exactly this during the week, and then I got distracted looking at a way to combine the workflows into one (based on something @crazy-max mentioned about using the docker meta action)

You should be able to test this on your fork by merging into `dev` over there, but you'll need to set up the docker hub flavoured secrets, too.

Maybe we could eventually employ something similar to what I've done here, so that building and pushing to GHCR on forks is easier:

https://github.com/PromoFaux/Matterhook.NET.MatterhookClient/blob/master/.github/workflows/build.yml#L45-L51

**Comment by ferferga** [comment]
@PromoFaux I assume it will work straightaway (the one that I have more doubts with is the "Test & Build workflow") as its exactly the same pipeline I used in Jellyfin Vue.

However, I will verify as you say 👍🏻. Give me some time and I'll report back.

**Comment by ferferga** [comment]
@PromoFaux Build went successful:

* Log: https://github.com/ferferga/docker-pi-hole/actions/runs/1402304875
* GHCR: https://github.com/ferferga/docker-pi-hole/pkgs/container/pihole
* DockerHub: https://hub.docker.com/repository/docker/ferferga/pihole

**Comment by crazy-max** [comment]
@PromoFaux When this PR is merged, I will open a new one with a single workflow as discussed.

**Review by PromoFaux — APPROVED** [review]
LGTM 

And @crazy-max - you're a superstar, thanks!

**Comment by ferferga** [comment]
@PromoFaux Are you interested in the PR for removing dangling images on cron?

Also — reminder for the syncing script [I made](https://gist.github.com/ferferga/7dc7bef353c2f41520a1a42d12f5e41c).

Please, can you run it locally to make GHCR a 1:1 mirror (including older images)? I would like to pin some devices to the older versions, and I prefer to have all of them pointing to GHCR instead of DockerHub.

**Comment by PromoFaux** [comment]
> @PromoFaux Are you interested in the PR for removing dangling images on cron?

Yep, go right ahead with that please.

I will take a look at that other script either later or tomorrow (most likely tomorrow as I'm currently operating on a hangover 😅)

**Comment by ferferga** [comment]
> > @PromoFaux Are you interested in the PR for removing dangling images on cron?
> 
> Yep, go right ahead with that please.
> 
> I will take a look at that other script either later or tomorrow (most likely tomorrow as I'm currently operating on a hangover 😅)

Great, thank you very much!

Don't hesitate in asking me any question about it!

**Comment by ferferga** [comment]
@PromoFaux Sorry for posting and annoy you here again, but I forgot to mention in the description that new packages are made private automatically when being published for the first time (at least it was like that when it was beta) 😁. Right now it's not accessible because of this so don't forget about it as well!

**Comment by PromoFaux** [comment]
I think there might have been a glitch somewhere along the line... the images appear to be there now? 

Regards your other script, I need to go through and tidy up what is on docker hub anyway - there are a lot of images that can be pruned (named containers that are also in multiarch images, for example), so will do that before syncing

**Comment by PromoFaux** [comment]
@ferferga I am a forgetful man - I will look at this - I'm just giving docker hub a tidy up first, as there are a lot of images that can disappear (duplicate digests/test builds etc) before I run your script to sync

@crazy-max I have been a big brave boy and [worked it out myself](https://github.com/pi-hole/docker-pi-hole/commit/27bdf81665830b8bf84c218754387dd8982b9f4a#diff-07e18c3cd0cb1d22e44acffda4355e2d0c61d769b2f257679630a542dafac291) (i think!)

**Comment by PromoFaux** [comment]
Ah... so running your script, I realise a major limitation - and I'm not sure how best to work around this... we need to sync multiarch. I realised after running this on my desktop that it was only syncing `amd64`. Any ideas?

**Comment by PromoFaux** [comment]
For anyone reading in the future: https://github.com/containers/skopeo

And the command that worked: `skopeo copy docker://pihole/pihole:latest docker://ghcr.io/pi-hole/pihole:latest --format oci --all`

Worked that into your script @ferferga, and it is happily syncing now 🎉

**Comment by ferferga** [comment]
@PromoFaux Thank you very much! For the proposal and very good catch!

Yes, as I used the normal ``docker pull``, it obviously pulled the image for the architecture of the system that's running. That was something I didn't thought of.

Thank you very much again as it will be very useful for us as well at Jellyfin.

**Comment by PromoFaux** [comment]
I actually got the idea after reading some of the comments/suggestions on your abovementioned PRs :)

**Comment by crazy-max** [comment]
@PromoFaux I left some comments https://github.com/pi-hole/docker-pi-hole/commit/27bdf81665830b8bf84c218754387dd8982b9f4a#diff-07e18c3cd0cb1d22e44acffda4355e2d0c61d769b2f257679630a542dafac291

**Comment by PromoFaux** [comment]
Thank you, I will look over them when I am next at a real computer. Is there anything super urgent you think needs addressing?

**Pull request merged**
