### PR TITLE
Add a ready to go Unbound compose file.

### PR DESCRIPTION
**Pull request by Gontier-Julien**
## Description
This commit add a ready to go Unbound compose file so we have an official docker-compose file with Pi-hole + Unbound to provide.

## Motivation and Context
Since Pi-hole V6 is a whole redesign and there is official documentation for running Pi-hole with Unbound, why not make an official compose file ready to go as discussed in #1430

## How Has This Been Tested?
Simply take the Unbound directory with all it files, and spin up the compose file!
To test simply do a `dig google.com @172.10.0.6 -p 53`

## Additional info
I've moved Caddy & Unbound on they're respective sub-directory and added a README.MD as it was more logical i think.
I'll add the according documentations on the `pihole/docs` repo soon.

I've also added choice in the compose file for Unbound such as:
- Images from @klutchell *(That i've chosen as default)*, there is the image from @MatthewVance & the one from Alpine Linux.
- There is according configs for both images *(tho only the one from @klutchell was tested since it default.)*
- For the `root.hints` file, there is an additional config for Debian user ready so they don't bother manually updating or anything the `root.hints` file.

I've choosen @klutchell image because both @PromoFaux and I use this image already so i've made it the default.

Let me know if there is any change needed to be made or anything! ^^

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly. *In progress*

### CODE REVIEW

**Comment by Gontier-Julien** [comment]
As for telling everyone where in the readme the example is present, please let me know so i can add it ^^

**Comment by PromoFaux** [comment]
Just to quote myself from the previous thread:

> Another target for this may actually be the pi-hole/docs repo under the Docker menu item

I really think the better target for this kind of information would be: https://docs.pi-hole.net/, but it should be one or the other and not both - else we have to keep two files in sync if any changes are made. My preference is docs.pi-hole.net. One of my long term goals is to move the majority of content in this repo's README into the docs repo, I just haven't got around to it yet

**Comment by Gontier-Julien** [comment]
> Just to quote myself from the previous thread:
> 
> > Another target for this may actually be the pi-hole/docs repo under the Docker menu item
> 
> I really think the better target for this kind of information would be: https://docs.pi-hole.net/, but it should be one or the other and not both - else we have to keep two files in sync if any changes are made. My preference is docs.pi-hole.net. One of my long term goals is to move the majority of content in this repo's README into the docs repo, I just haven't got around to it yet

Oh alright, no problem!
I'll merge this on the pi-hole doc repo them!
But after the holidays haha & happy holiday to you! ^^
Closing this here then.

**Comment by asavpatel92** [comment]
@Gontier-Julien hi there, did you end up creating a PR to docs repo? I tried searching there but couldn't find compose file for unbound.

**Comment by Gontier-Julien** [comment]
> @Gontier-Julien hi there, did you end up creating a PR to docs repo? I tried searching there but couldn't find compose file for unbound.

Hi, not yet, tbh i completely forgot about it haha.
I'll do it if i find sometime or don't forget about it again. But if anyone want to do it feel free to do so.

**Pull request closed without merging**
