### PR TITLE
Remove obsolete "version" value from example docker-compose.yml

### LINKED ISSUE #1562: Remove obsolete "version" value from example docker-compose.yml in README.md
This is a: **Bug**  

## Details

`Version` in `docker-compose.yml` files has been obsolete for quite some time now. Per [the documentation](https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md):

> Compose doesn't use version to select an exact schema to validate the Compose file, but prefers the most recent schema when it's implemented.
## Related Issues
- [x] I have searched this repository/Pi-hole forums for existing issues and pull requests that look similar 

## How to reproduce the issue 

View docker-pi-hole's [README.md](https://github.com/pi-hole/docker-pi-hole/blob/master/README.md) and note that the example `docker-compose.yml` includes an unnecessary `version` entry.

### PR DESCRIPTION
**Pull request by lemondjeff**
## Description
Remove obsolete "version" value from example docker-compose.yml in README.md and from .yml files in
examples since "Compose doesn't use version to select an exact schema to validate the Compose file, but prefers the most recent schema when it's implemented."

See: https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md

## Motivation and Context
Updates the example `docker-compose.yml` to be consistent with current version of docker-compose.
Resolves #1562
## How Has This Been Tested?
Viewed `README.md` and verified the change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Please check the details link on the DCO check for instructions on how to appease the DCO bot :)

Can you also provide a similar PR against the `development-v6` branch? It's quite unlikely for there to be another `dev` -> `master` release flow, but `development-v6` is under active development

**Comment by lemondjeff** [comment]
Thanks, first time submitting a PR here, so I appreciate the help. I'll create another PR against the `development-v6` branch shortly.

**Comment by lemondjeff** [comment]
> Thanks, first time submitting a PR here, so I appreciate the help. I'll create another PR against the `development-v6` branch shortly.

I created [PR #1568](https://github.com/pi-hole/docker-pi-hole/pull/1568) based on the `development-v6` branch.

**Review by rdwebdesign — DISMISSED** [review]

**Comment by PromoFaux** [comment]
Thanks! Couple more places to check... look under the `examples` directory (same for the `development-v6` branch 🙂)

**Comment by lemondjeff** [comment]
> Thanks! Couple more places to check... look under the `examples` directory (same for the `development-v6` branch 🙂)

Done, updated the PR  to remove version from .yml files in `examples` directory.

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
