### PR TITLE
Run `_gravityonboot` oneshot in background

### PR DESCRIPTION
**Pull request by PromoFaux**
Attempts to solve https://github.com/pi-hole/docker-pi-hole/issues/1149 by adding an infinite value to the timeout of this script.

### CODE REVIEW

**Comment by PromoFaux** [comment]
@edgd1er - Please try this on your Pi

**Comment by PromoFaux** [comment]
It is not this. Still times out:

image

**Comment by PromoFaux** [comment]
Should work now...

**Comment by edgd1er** [comment]
@PromoFaux , a bit late, nonetheless I confirm the fix is ok on my rpi3, no more timeout while updating the database. Thanks.

**Pull request merged**
