### PR TITLE
Update README to explain the version numbers slightly more accurately

### PR DESCRIPTION
**Pull request by PromoFaux**
See: https://github.com/pi-hole/docker-pi-hole/issues/1249

The documentation as it is is confusing, the container does not follow any kind of semver rule, and also previous tags are not re-tagged to include "bugfixes".

New builds are just that... new builds. We give them some kind of version number for easy switching back and forth between them

### CODE REVIEW

**Comment by PromoFaux** [comment]
a

**Comment by PromoFaux** [comment]
a

**Comment by PromoFaux** [comment]
a

**Comment by mwolter805** [comment]
Hello, It appears there may be a bit more ambiguity regarding versioning as there will never be a 2022.12.0 version. In order to programmatically decipher versions, it might be useful to say something like the following:

Container versioning does not follow [semver](https://semver.org), and can follow two different formats. 

Version format A has two octets, with the first octet representing the year and the second octet representing the month of the release. For example 2022.12

Version format B has three octets, with the first two octets following format A and a third octet representing the update number for the particular month. For example 2022.11.2

Note: the third octet of format B will only be >= 1. For example, 2022.12.0 is invalid.

**Pull request merged**
