### PR TITLE
Move gravity on boot to a @reboot cron job

### PR DESCRIPTION
**Pull request by mdzw**
## Description
This is a proposed solution to #834.

## Motivation and Context
Gravity update is relying on pihole-FTL for its DNS resolution. If "gravity on boot" is enabled, we shouldn't try to run it before the long-running instance of pihole-FTL is starting.

Copied from my comment on the issue:

I believe the correct way to solve this issue is to change when "Gravity on Boot" is run.

The s6 init system has [different stages](https://github.com/just-containers/s6-overlay#init-stages). Currently, "gravity on boot" is [run](https://github.com/pi-hole/docker-pi-hole/blob/master/s6/debian-root/etc/cont-init.d/20-start.sh#L18) during Stage 2.ii: **cont-init.d**. One instance of pihole-FTL is started during cont-init, but it is only there to check the validity of the config files; it exits soon after starting. The final "service mode" instance of pihole-FTL is not started until **Stage 2.iii**, when the supervisor starts doing work.

If gravity.sh is counting on FTL to do its DNS lookups, then we should not run gravity until the supervised instance of FTL is running. We can accomplish this by **moving "Gravity on Boot" to a `@reboot` line in /etc/cron.d/gravity-on-boot**, and making that file's existence dependent on the value of SKIPGRAVITYONBOOT.

This will work because cron isn't started until we've reached Stage 2.iii.

edit: PR incoming.

## How Has This Been Tested?
A thorough examination of the startup sequence for Docker pihole, gravity, and pihole-FTL.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project. (Maybe?)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mdzw** [comment]
It looks like the cron job is not getting run (there's no `/var/log/pihole_updateGravity.log` file), but I don't see any indication of why.

**Comment by PromoFaux** [comment]
> there's no `/var/log/pihole_updateGravity.log` file

Sure about that?

https://github.com/pi-hole/docker-pi-hole/pull/836#issuecomment-821268702

**Comment by PromoFaux** [comment]
What _does_ happen, though, is that setting `SKIPGRAVITYONBOOT` causes it to boot loop:

image

**Comment by mdzw** [comment]
> What _does_ happen, though, is that setting `SKIPGRAVITYONBOOT` causes it to boot loop:

d'oh, probably should check for that file before trying to `rm` it, or put `|| true` at the end.

**Comment by PromoFaux** [comment]
Initially, though, it does appear to fix this issue. I can't make it fall over with this build in the same way I was able to make it fall over yesterday with v5.8.

Can you sort the issue with `SKIPGRAVITYONBOOT`, and then we can try this on the `:dev` tag to see if it fixes it for others

**Comment by PromoFaux** [comment]
Yep, looks to be working, thanks. Now we wait for the CI to finish.

**Review by PromoFaux — APPROVED** [review]
Go for `:dev` we can always revert if needed

**Pull request merged**
