### PR TITLE
Set FTL REPLY addresses instead of setupVars.conf.

### PR DESCRIPTION
**Pull request by dschaper**
## Description

Set FTL variable for ServerIP.

## Motivation and Context

We used to use the setupVars.conf value to determine the response IP address. FTL changed to determine this address itself but included an override set in the ftl.conf files. This PR changes the settings to use the flags in ftl.conf instead of setupVars.conf

## How Has This Been Tested?

Doing a `dig` for `pi.hole` for a bridged container would return the IP address of the container. Adding the proper configs now returns the value intended for `pi.hole` queries and allows users to use `pi.hole` for the web interface again.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by lightswitch05 — APPROVED** [review]
Looks good to me 👍

**Comment by dschaper** [comment]
Will pushing to dev create a new container?

**Comment by lightswitch05** [comment]
Yes, it will kick off a dev build and be included in the nightly builds

**Comment by lightswitch05** [comment]
These are the branch patterns that get built on push:

```
    branches:
      - master
      - dev
      - v*
      - beta-v*
      - release/*
```

**Comment by dschaper** [comment]
Did this go to the beta image or is it just in the nightly?

**Comment by mislav** [comment]
@dschaper Confirming beta-v5.9 fixes my problem (`192.168.1.25` is expected):
```
$ nslookup pi.hole localhost
Server:		localhost
Address:	::1#53

Name:	pi.hole
Address: 192.168.1.25
Name:	pi.hole
Address: ::
```
Thank you!

**Comment by scara** [comment]
Hello Everyone,
should `REPLY_ADDR*` be documented into the README too?

HTH,
Matteo

**Pull request merged**
