### PR TITLE
Remove obsolete "version" value from example docker-compose.yml since…

### PR DESCRIPTION
**Pull request by lemondjeff**
## Description

Remove obsolete "version" value from example docker-compose.yml in README.md and from `examples/docker-compose-caddy-proxy.yml` since "Compose doesn't use version to select an exact schema to validate the Compose file, but prefers the most recent schema when it's implemented."
## Motivation and Context
Fixes issue #1562.

## How Has This Been Tested?
Viewed `README.md` and verified that `Version` is no longer specified in the example `docker-compose.yml`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by rdwebdesign — APPROVED** [review]

**Comment by lemondjeff** [comment]
Updated PR to remove version from `examples/docker-compose-caddy-proxy.yml` as well.

**Comment by PromoFaux** [comment]
image

You may be missing commits from `development-v6` here? Not sure.. I could update your branch with a merge commit, but might be cleaner to rebase and force push...

**Comment by PromoFaux** [comment]
(odd message though, as I don't recall merging anything into `development-v6` since you created this PR!!)

**Comment by lemondjeff** [comment]
> (odd message though, as I don't recall merging anything into `development-v6` since you created this PR!!)

Yeah, I'm not sure what's wrong. I checked out a new local copy of the `development-v6-issue-1562`, rebased and made and reverted a change, then force pushed again.

**Comment by rdwebdesign** [comment]
@lemondjeff 

Looking at your fork, your [branch `development-v6`](https://github.com/lemondjeff/docker-pi-hole/tree/development-v6) is 4 commits behind our branch:

image

Did you try to use the "Sync fork" button to update your branch?

**Comment by lemondjeff** [comment]
> Did you try to use the "Sync fork" button to update your branch?

Hmm, the `Sync fork` button for my [development-v6-issue-1562 branch](https://github.com/lemondjeff/docker-pi-hole/tree/development-v6-issue-1562) seems to want to sync with `pi-hole/docker-pi-hole:master`, even though I created the branch from `pi-hole/docker-pi-hole:development-v6`. I'm not sure how to fix this.

**Comment by lemondjeff** [comment]
I just used the `Merge branch` button, which added more commits on top of my original commit. I give up, I'm going to close this PR and start with a new branch from `development-v6`.

**Comment by lemondjeff** [comment]
Opened [a new PR](https://github.com/pi-hole/docker-pi-hole/pull/1569).

**Pull request closed without merging**
